"""renamed some variables

Revision ID: 05e735594e70
Revises: 38cc44240b0b
Create Date: 2019-05-05 02:38:22.808083

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '05e735594e70'
down_revision = '38cc44240b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('line1', sa.String(length=64), nullable=True))
    op.add_column('address', sa.Column('line2', sa.String(length=64), nullable=True))
    op.drop_column('address', 'address1')
    op.drop_column('address', 'address2')
    op.add_column('task', sa.Column('dropoff_address_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('pickup_address_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_dropoffAddress_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_pickupAddress_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'address', ['dropoff_address_id'], ['id'])
    op.create_foreign_key(None, 'task', 'address', ['pickup_address_id'], ['id'])
    op.drop_column('task', 'pickupTown')
    op.drop_column('task', 'dropoffAddress_id')
    op.drop_column('task', 'destinationAddress2')
    op.drop_column('task', 'pickupAddress_id')
    op.drop_column('task', 'pickupPostcode')
    op.drop_column('task', 'destinationPostcode')
    op.drop_column('task', 'destinationAddress1')
    op.drop_column('task', 'pickupAddress1')
    op.drop_column('task', 'destinationTown')
    op.drop_column('task', 'pickupAddress2')
    op.add_column('user', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'address_id')
    op.add_column('task', sa.Column('pickupAddress2', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('destinationTown', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('pickupAddress1', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('destinationAddress1', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('destinationPostcode', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('pickupPostcode', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('pickupAddress_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('destinationAddress2', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('dropoffAddress_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('pickupTown', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_pickupAddress_id_fkey', 'task', 'address', ['pickupAddress_id'], ['id'])
    op.create_foreign_key('task_dropoffAddress_id_fkey', 'task', 'address', ['dropoffAddress_id'], ['id'])
    op.drop_column('task', 'pickup_address_id')
    op.drop_column('task', 'dropoff_address_id')
    op.add_column('address', sa.Column('address2', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address1', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('address', 'line2')
    op.drop_column('address', 'line1')
    # ### end Alembic commands ###
