"""address user

Revision ID: 0a00ab117df0
Revises: 1e12b4a5704d
Create Date: 2019-05-03 19:38:04.488274

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0a00ab117df0'
down_revision = '1e12b4a5704d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_homeAddress_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'address', ['address_id'], ['id'])
    op.drop_column('user', 'homeAddress_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('homeAddress_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_homeAddress_id_fkey', 'user', 'address', ['homeAddress_id'], ['id'])
    op.drop_column('user', 'address_id')
    # ### end Alembic commands ###
