"""Patch model

Revision ID: 119481e63b80
Revises: 67b5e4b828e2
Create Date: 2019-10-23 21:19:53.301076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119481e63b80'
down_revision = '67b5e4b828e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patch')
    # ### end Alembic commands ###
