"""time deleted on delete queue

Revision ID: 13f9bd5bf278
Revises: 599d761294c3
Create Date: 2019-05-21 20:07:41.460550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f9bd5bf278'
down_revision = '599d761294c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete_flags', sa.Column('time_deleted', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_delete_flags_time_deleted'), 'delete_flags', ['time_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delete_flags_time_deleted'), table_name='delete_flags')
    op.drop_column('delete_flags', 'time_deleted')
    # ### end Alembic commands ###
