"""flagged for deletion on session

Revision ID: 15b4b785e436
Revises: 99d7f2da1e27
Create Date: 2019-01-21 22:04:33.036589

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '15b4b785e436'
down_revision = '99d7f2da1e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('flaggedForDeletion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'flaggedForDeletion')
    # ### end Alembic commands ###
