"""patch is now foreign key on user

Revision ID: 1b5ecd4a7405
Revises: 3e6a539f219d
Create Date: 2019-10-23 21:41:17.015275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5ecd4a7405'
down_revision = '3e6a539f219d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('patch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'patch', ['patch_id'], ['id'])
    op.drop_column('user', 'patch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('patch', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'patch_id')
    # ### end Alembic commands ###
