"""deliverables uuid foreign key

Revision ID: 1c1264d0041c
Revises: dcb02d01f475
Create Date: 2019-08-15 00:27:23.842908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c1264d0041c'
down_revision = 'dcb02d01f475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable', sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('deliverable_task_fkey', 'deliverable', type_='foreignkey')
    op.create_foreign_key(None, 'deliverable', 'task', ['task_id'], ['uuid'])
    op.drop_column('deliverable', 'task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable', sa.Column('task', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deliverable', type_='foreignkey')
    op.create_foreign_key('deliverable_task_fkey', 'deliverable', 'task', ['task'], ['id'])
    op.drop_column('deliverable', 'task_id')
    # ### end Alembic commands ###
