"""cancelled_time and rejected_time for task

Revision ID: 1d8d7c4b6f26
Revises: e83dca7abb9f
Create Date: 2020-03-19 23:24:36.656294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8d7c4b6f26'
down_revision = 'e83dca7abb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('cancelled_time', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('rejected_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'rejected_time')
    op.drop_column('task', 'cancelled_time')
    # ### end Alembic commands ###
