"""no notes for now

Revision ID: 1e12b4a5704d
Revises: 4e8cd0eb8fc6
Create Date: 2019-05-03 19:24:19.032472

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e12b4a5704d'
down_revision = '4e8cd0eb8fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('note_deliverable_fkey', 'note', type_='foreignkey')
    op.drop_constraint('note_session_fkey', 'note', type_='foreignkey')
    op.drop_constraint('note_user_fkey', 'note', type_='foreignkey')
    op.drop_constraint('note_task_fkey', 'note', type_='foreignkey')
    op.drop_constraint('note_vehicle_fkey', 'note', type_='foreignkey')
    op.drop_column('note', 'deliverable')
    op.drop_column('note', 'user')
    op.drop_column('note', 'vehicle')
    op.drop_column('note', 'session')
    op.drop_column('note', 'task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('task', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('note', sa.Column('session', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('note', sa.Column('vehicle', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('note', sa.Column('user', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('note', sa.Column('deliverable', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('note_vehicle_fkey', 'note', 'vehicle', ['vehicle'], ['uuid'])
    op.create_foreign_key('note_task_fkey', 'note', 'task', ['task'], ['uuid'])
    op.create_foreign_key('note_user_fkey', 'note', 'user', ['user'], ['uuid'])
    op.create_foreign_key('note_session_fkey', 'note', 'session', ['session'], ['uuid'])
    op.create_foreign_key('note_deliverable_fkey', 'note', 'deliverable', ['deliverable'], ['id'])
    # ### end Alembic commands ###
