"""count int value on Deliverable

Revision ID: 1e237d39052c
Revises: e165d74da4e1
Create Date: 2021-06-17 21:10:20.606074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e237d39052c'
down_revision = 'e165d74da4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliverable', 'count')
    # ### end Alembic commands ###
