"""http_response_code on LogEntry. no code on HTTPRequestType

Revision ID: 1e7d54e6cc89
Revises: 6eb00d300cb0
Create Date: 2020-11-05 19:28:08.774325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7d54e6cc89'
down_revision = '6eb00d300cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('http_request_type', 'code')
    op.add_column('log_entry', sa.Column('http_response_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entry', 'http_response_code')
    op.add_column('http_request_type', sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
