"""change profile_picture_url to profile_picture_key

Revision ID: 20849c301848
Revises: 583ff7aeb19b
Create Date: 2020-09-29 00:41:06.013974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20849c301848'
down_revision = '583ff7aeb19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture_key', sa.String(length=128), nullable=True))
    op.drop_column('user', 'profile_picture_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture_url', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'profile_picture_key')
    # ### end Alembic commands ###
