"""address user

Revision ID: 38cc44240b0b
Revises: 0a00ab117df0
Create Date: 2019-05-04 22:30:57.802505

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '38cc44240b0b'
down_revision = '0a00ab117df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_address_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_address_id_fkey', 'user', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###
