"""new Contact table and foreign key to Contact for Task requester

Revision ID: 393a7afd189b
Revises: 4109f40f5bd8
Create Date: 2020-10-13 17:45:41.707990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393a7afd189b'
down_revision = '4109f40f5bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('telephone_number', sa.String(length=64), nullable=True),
    sa.Column('mobile_number', sa.String(length=64), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('requester_contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'contact', ['requester_contact_id'], ['id'])
    op.drop_column('task', 'patient_name')
    op.drop_column('task', 'destination_contact_number')
    op.drop_column('task', 'destination_contact_name')
    op.drop_column('task', 'contact_number')
    op.drop_column('task', 'contact_name')
    op.drop_column('task', 'patient_contact_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('patient_contact_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('contact_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('contact_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('destination_contact_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('destination_contact_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('patient_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'requester_contact_id')
    op.drop_table('contact')
    # ### end Alembic commands ###
