"""initial

Revision ID: 3e3aa62e7203
Revises: 
Create Date: 2018-09-16 18:10:47.388497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3aa62e7203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address1', sa.String(length=64), nullable=True),
    sa.Column('address2', sa.String(length=64), nullable=True),
    sa.Column('town', sa.String(length=64), nullable=True),
    sa.Column('postcode', sa.String(length=7), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('assignedVehicle', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pickupAddress1', sa.String(length=64), nullable=True),
    sa.Column('pickupAddress2', sa.String(length=64), nullable=True),
    sa.Column('pickupTown', sa.String(length=64), nullable=True),
    sa.Column('pickupPostcode', sa.String(length=7), nullable=True),
    sa.Column('destinationAddress1', sa.String(length=64), nullable=True),
    sa.Column('destinationAddress2', sa.String(length=64), nullable=True),
    sa.Column('destinationTown', sa.String(length=64), nullable=True),
    sa.Column('destinationPostcode', sa.String(length=7), nullable=True),
    sa.Column('patch', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('finalDuration', sa.Time(), nullable=True),
    sa.Column('miles', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_timestamp'), 'task', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_timestamp'), table_name='task')
    op.drop_table('task')
    op.drop_table('rider')
    # ### end Alembic commands ###
