"""display_name for User model

Revision ID: 3e6a539f219d
Revises: 119481e63b80
Create Date: 2019-10-23 21:20:29.406111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6a539f219d'
down_revision = '119481e63b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
