"""relay_next Task to Task relationship

Revision ID: 4109f40f5bd8
Revises: ac32c8706044
Create Date: 2020-10-12 23:46:24.109901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4109f40f5bd8'
down_revision = 'ac32c8706044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('relay_previous_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['relay_previous_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'relay_previous_uuid')
    # ### end Alembic commands ###
