"""patch as foreign key on task

Revision ID: 4529a80c2aad
Revises: d7552815fe15
Create Date: 2020-03-25 15:14:40.310387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4529a80c2aad'
down_revision = 'd7552815fe15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('patch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'patch', ['patch_id'], ['id'])
    op.drop_column('task', 'patch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('patch', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'patch_id')
    # ### end Alembic commands ###
