"""added task parent table

Revision ID: 475d042f819a
Revises: 393a7afd189b
Create Date: 2020-10-20 20:58:08.180052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475d042f819a'
down_revision = '393a7afd189b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_parent')
    # ### end Alembic commands ###
