"""added LogEntry model and HTTPRequestType model

Revision ID: 4c0c26845583
Revises: 6995a0f6f913
Create Date: 2020-11-05 17:56:13.552623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c0c26845583'
down_revision = '6995a0f6f913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('http_request_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('log_entry',
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flagged_for_deletion', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parent_type', sa.Integer(), nullable=True),
    sa.Column('parent_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('calling_user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('http_request_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calling_user_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['http_request_type_id'], ['http_request_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_log_entry_time_created'), 'log_entry', ['time_created'], unique=False)
    op.create_index(op.f('ix_log_entry_time_modified'), 'log_entry', ['time_modified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entry_time_modified'), table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_time_created'), table_name='log_entry')
    op.drop_table('log_entry')
    op.drop_table('http_request_type')
    # ### end Alembic commands ###
