"""properly named delivery_location_uuid and delivery_location on Task

Revision ID: 4d2f69dc0c76
Revises: 94bf8e9e0043
Create Date: 2021-01-31 15:06:43.998809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d2f69dc0c76'
down_revision = '94bf8e9e0043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('address_uuid_key', 'address', type_='unique')
    op.drop_column('address', 'uuid')
    op.add_column('location', sa.Column('location_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'location_type', ['location_type_id'], ['id'])
    op.add_column('task', sa.Column('delivery_location_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('task', sa.Column('pickup_location_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('task_saved_location_dropoff_uuid_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_pickup_address_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_saved_location_pickup_uuid_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_dropoff_address_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'location', ['pickup_location_uuid'], ['uuid'])
    op.create_foreign_key(None, 'task', 'location', ['delivery_location_uuid'], ['uuid'])
    op.drop_column('task', 'pickup_address_id')
    op.drop_column('task', 'dropoff_address_id')
    op.drop_column('task', 'saved_location_pickup_uuid')
    op.drop_column('task', 'saved_location_dropoff_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('saved_location_dropoff_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('saved_location_pickup_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('dropoff_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('pickup_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_dropoff_address_id_fkey', 'task', 'address', ['dropoff_address_id'], ['id'])
    op.create_foreign_key('task_saved_location_pickup_uuid_fkey', 'task', 'location', ['saved_location_pickup_uuid'], ['uuid'])
    op.create_foreign_key('task_pickup_address_id_fkey', 'task', 'address', ['pickup_address_id'], ['id'])
    op.create_foreign_key('task_saved_location_dropoff_uuid_fkey', 'task', 'location', ['saved_location_dropoff_uuid'], ['uuid'])
    op.drop_column('task', 'pickup_location_uuid')
    op.drop_column('task', 'delivery_location_uuid')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'location_type_id')
    op.add_column('address', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('address_uuid_key', 'address', ['uuid'])
    op.drop_table('location_type')
    # ### end Alembic commands ###
