"""remove session references on task/user

Revision ID: 4f96df1bc3b6
Revises: 92b8d39ea20b
Create Date: 2020-09-02 00:17:02.281417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f96df1bc3b6'
down_revision = '92b8d39ea20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_session_uuid_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'session_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('session_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_session_uuid_fkey', 'task', 'session', ['session_uuid'], ['uuid'])
    # ### end Alembic commands ###
