"""foreign key link between Task and TasksParent

Revision ID: 56d12dc9e20a
Revises: 475d042f819a
Create Date: 2020-10-20 20:59:20.829243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d12dc9e20a'
down_revision = '475d042f819a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'tasks_parent', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'parent_id')
    # ### end Alembic commands ###
