"""active flag on delete queue

Revision ID: 599d761294c3
Revises: ff03648618e7
Create Date: 2019-05-18 20:48:27.971038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599d761294c3'
down_revision = 'ff03648618e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete_flags', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete_flags', 'active')
    # ### end Alembic commands ###
