"""rename delivery back to dropoff

Revision ID: 5df6df91a533
Revises: 4d2f69dc0c76
Create Date: 2021-02-01 17:57:46.648532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5df6df91a533'
down_revision = '4d2f69dc0c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('dropoff_location_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('task_delivery_location_uuid_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'location', ['dropoff_location_uuid'], ['uuid'])
    op.drop_column('task', 'delivery_location_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('delivery_location_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_delivery_location_uuid_fkey', 'task', 'location', ['delivery_location_uuid'], ['uuid'])
    op.drop_column('task', 'dropoff_location_uuid')
    # ### end Alembic commands ###
