"""removed address mixin for location. added ward.

Revision ID: 65e41456e6b2
Revises: d6664040d05a
Create Date: 2019-08-22 10:37:56.071280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e41456e6b2'
down_revision = 'd6664040d05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('ward', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'ward')
    # ### end Alembic commands ###
