"""unique constraint on priority labels. what3words on addresses

Revision ID: 67b5e4b828e2
Revises: cd7000cb83b3
Create Date: 2019-10-20 00:49:33.086135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b5e4b828e2'
down_revision = 'cd7000cb83b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('what3words', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'priority', ['label'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'priority', type_='unique')
    op.drop_column('address', 'what3words')
    # ### end Alembic commands ###
