"""added order_in_relay value to Task

Revision ID: 6995a0f6f913
Revises: 95b81b63b36d
Create Date: 2020-10-21 20:36:10.915309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6995a0f6f913'
down_revision = '95b81b63b36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('order_in_relay', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'order_in_relay')
    # ### end Alembic commands ###
