"""remove CommonMixin from LogEntry and add time_created only

Revision ID: 6eb00d300cb0
Revises: 4c0c26845583
Create Date: 2020-11-05 19:08:37.665639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6eb00d300cb0'
down_revision = '4c0c26845583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_entry_time_modified', table_name='log_entry')
    op.drop_column('log_entry', 'time_modified')
    op.drop_column('log_entry', 'flagged_for_deletion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entry', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('log_entry', sa.Column('time_modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_log_entry_time_modified', 'log_entry', ['time_modified'], unique=False)
    # ### end Alembic commands ###
