"""Added contact name and number to task

Revision ID: 6f9bc5659e25
Revises: 4a4f0852e993
Create Date: 2019-01-10 22:53:04.934327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9bc5659e25'
down_revision = '4a4f0852e993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('contactName', sa.String(length=64), nullable=True))
    op.add_column('task', sa.Column('contactNumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'contactNumber')
    op.drop_column('task', 'contactName')
    # ### end Alembic commands ###
