"""ServerSettings and Locale tables

Revision ID: 73213b252ed5
Revises: b8986c9de736
Create Date: 2020-04-23 02:20:26.011536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73213b252ed5'
down_revision = 'b8986c9de736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locale',
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_modified', sa.DateTime(), nullable=True),
    sa.Column('flagged_for_deletion', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_locale_time_created'), 'locale', ['time_created'], unique=False)
    op.create_index(op.f('ix_locale_time_modified'), 'locale', ['time_modified'], unique=False)
    op.create_table('server_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_modified', sa.DateTime(), nullable=True),
    sa.Column('organisation_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('favicon', sa.String(), nullable=True),
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_name')
    )
    op.create_index(op.f('ix_server_settings_time_created'), 'server_settings', ['time_created'], unique=False)
    op.create_index(op.f('ix_server_settings_time_modified'), 'server_settings', ['time_modified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_settings_time_modified'), table_name='server_settings')
    op.drop_index(op.f('ix_server_settings_time_created'), table_name='server_settings')
    op.drop_table('server_settings')
    op.drop_index(op.f('ix_locale_time_modified'), table_name='locale')
    op.drop_index(op.f('ix_locale_time_created'), table_name='locale')
    op.drop_table('locale')
    # ### end Alembic commands ###
