"""DeleteFlags uuid remove unique constraint

Revision ID: 794bafaf28e4
Revises: d26942cec718
Create Date: 2020-04-07 20:32:39.862843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794bafaf28e4'
down_revision = 'd26942cec718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('delete_flags_uuid_key', 'delete_flags', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('delete_flags_uuid_key', 'delete_flags', ['uuid'])
    # ### end Alembic commands ###
