"""flagged_for_deletion attr on Deliverable model

Revision ID: 8c1e8048ad3d
Revises: 8af2aaba6f0e
Create Date: 2019-11-21 20:09:12.607896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1e8048ad3d'
down_revision = '8af2aaba6f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable', sa.Column('flagged_for_deletion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliverable', 'flagged_for_deletion')
    # ### end Alembic commands ###
