"""author field foreign key

Revision ID: 90adc2e968b8
Revises: 8b4d777026ad
Create Date: 2020-04-15 19:46:01.025354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90adc2e968b8'
down_revision = '8b4d777026ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('comment_author_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['author_uuid'], ['uuid'])
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_author_fkey', 'comment', 'user', ['author'], ['uuid'])
    op.drop_column('comment', 'author_uuid')
    # ### end Alembic commands ###
