"""change contact_name and contact_number to foreign key contact on Location model

Revision ID: 91032dbedd67
Revises: bd0192e6895d
Create Date: 2020-11-26 18:11:30.107581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91032dbedd67'
down_revision = 'bd0192e6895d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'contact', ['contact_id'], ['id'])
    op.drop_column('location', 'contact_name')
    op.drop_column('location', 'contact_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('contact_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('contact_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'contact_id')
    # ### end Alembic commands ###
