"""add author, assigned_coordinators and assigned_riders to task

Revision ID: 9144baa0b1fc
Revises: 4f96df1bc3b6
Create Date: 2020-09-02 15:37:20.055902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9144baa0b1fc'
down_revision = '4f96df1bc3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_coordinator_assignees',
    sa.Column('task_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['task_uuid'], ['task.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('task_uuid', 'user_uuid')
    )
    op.create_table('task_rider_assignees',
    sa.Column('task_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['task_uuid'], ['task.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('task_uuid', 'user_uuid')
    )
    op.drop_table('task_assignees')
    op.add_column('task', sa.Column('author_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['author_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'author_uuid')
    op.create_table('task_assignees',
    sa.Column('task_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_uuid'], ['task.uuid'], name='task_assignees_task_uuid_fkey'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name='task_assignees_user_uuid_fkey'),
    sa.PrimaryKeyConstraint('task_uuid', 'user_uuid', name='task_assignees_pkey')
    )
    op.drop_table('task_rider_assignees')
    op.drop_table('task_coordinator_assignees')
    # ### end Alembic commands ###
