"""removed no longer needed timestamp attrs

Revision ID: 916264802e42
Revises: 3ddb016baa76
Create Date: 2020-04-07 19:12:35.500920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '916264802e42'
down_revision = '3ddb016baa76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete_flags', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_delete_flags_time_created'), 'delete_flags', ['time_created'], unique=False)
    op.drop_index('ix_delete_flags_timestamp', table_name='delete_flags')
    op.drop_column('delete_flags', 'timestamp')
    op.drop_index('ix_location_timestamp', table_name='location')
    op.drop_column('location', 'timestamp')
    op.drop_index('ix_session_timestamp', table_name='session')
    op.drop_column('session', 'timestamp')
    op.drop_index('ix_user_timestamp', table_name='user')
    op.drop_column('user', 'timestamp')
    op.drop_index('ix_vehicle_timestamp', table_name='vehicle')
    op.drop_column('vehicle', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_vehicle_timestamp', 'vehicle', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_user_timestamp', 'user', ['timestamp'], unique=False)
    op.add_column('session', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_session_timestamp', 'session', ['timestamp'], unique=False)
    op.add_column('location', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_location_timestamp', 'location', ['timestamp'], unique=False)
    op.add_column('delete_flags', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_delete_flags_timestamp', 'delete_flags', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_delete_flags_time_created'), table_name='delete_flags')
    op.drop_column('delete_flags', 'time_created')
    # ### end Alembic commands ###
