"""save_location_pickup and saved_location_dropoff foreign key relationships on Task model

Revision ID: 94bf8e9e0043
Revises: ae8780b9274f
Create Date: 2021-01-19 00:55:30.702517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94bf8e9e0043'
down_revision = 'ae8780b9274f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('saved_location_dropoff_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('task', sa.Column('saved_location_pickup_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'task', 'location', ['saved_location_pickup_uuid'], ['uuid'])
    op.create_foreign_key(None, 'task', 'location', ['saved_location_dropoff_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'saved_location_pickup_uuid')
    op.drop_column('task', 'saved_location_dropoff_uuid')
    # ### end Alembic commands ###
