"""added CommonMixing class to TasksParent

Revision ID: 95b81b63b36d
Revises: 56d12dc9e20a
Create Date: 2020-10-21 15:36:04.827123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b81b63b36d'
down_revision = '56d12dc9e20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_parent', sa.Column('flagged_for_deletion', sa.Boolean(), nullable=True))
    op.add_column('tasks_parent', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks_parent', sa.Column('time_modified', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_parent_time_created'), 'tasks_parent', ['time_created'], unique=False)
    op.create_index(op.f('ix_tasks_parent_time_modified'), 'tasks_parent', ['time_modified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_parent_time_modified'), table_name='tasks_parent')
    op.drop_index(op.f('ix_tasks_parent_time_created'), table_name='tasks_parent')
    op.drop_column('tasks_parent', 'time_modified')
    op.drop_column('tasks_parent', 'time_created')
    op.drop_column('tasks_parent', 'flagged_for_deletion')
    # ### end Alembic commands ###
