"""is_active

Revision ID: 9b14e62fb2b7
Revises: cbf2b48b4574
Create Date: 2019-01-12 22:22:51.481355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b14e62fb2b7'
down_revision = 'cbf2b48b4574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('user', sa.Column('roles', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roles')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
