"""rename flagged_for_deletion to deleted

Revision ID: 9cc96dcc78ff
Revises: dca2e3e8a5e8
Create Date: 2020-11-15 15:04:43.756221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc96dcc78ff'
down_revision = 'dca2e3e8a5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('comment', 'flagged_for_deletion')
    op.add_column('deliverable', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('deliverable', 'flagged_for_deletion')
    op.add_column('deliverable_type', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('deliverable_type', 'flagged_for_deletion')
    op.add_column('locale', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('locale', 'flagged_for_deletion')
    op.add_column('location', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('location', 'flagged_for_deletion')
    op.add_column('patch', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('patch', 'flagged_for_deletion')
    op.add_column('priority', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('priority', 'flagged_for_deletion')
    op.add_column('task', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('task', 'flagged_for_deletion')
    op.add_column('tasks_parent', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('tasks_parent', 'flagged_for_deletion')
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('user', 'flagged_for_deletion')
    op.add_column('vehicle', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('vehicle', 'flagged_for_deletion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'deleted')
    op.add_column('user', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'deleted')
    op.add_column('tasks_parent', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks_parent', 'deleted')
    op.add_column('task', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('task', 'deleted')
    op.add_column('priority', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('priority', 'deleted')
    op.add_column('patch', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('patch', 'deleted')
    op.add_column('location', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('location', 'deleted')
    op.add_column('locale', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('locale', 'deleted')
    op.add_column('deliverable_type', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('deliverable_type', 'deleted')
    op.add_column('deliverable', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('deliverable', 'deleted')
    op.add_column('comment', sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'deleted')
    # ### end Alembic commands ###
