"""timezone test

Revision ID: a38edafcb11e
Revises: aa4a8f541ac1
Create Date: 2020-05-31 18:25:25.785169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a38edafcb11e'
down_revision = 'aa4a8f541ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('datetime', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_task_datetime'), 'task', ['datetime'], unique=False)
    op.drop_index('ix_task_time_of_call', table_name='task')
    op.drop_column('task', 'time_of_call')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('time_of_call', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_task_time_of_call', 'task', ['time_of_call'], unique=False)
    op.drop_index(op.f('ix_task_datetime'), table_name='task')
    op.drop_column('task', 'datetime')
    # ### end Alembic commands ###
