"""relay_next and relay_previous foreign key on Task to Task

Revision ID: a395cd9f83ac
Revises: ac32c8706044
Create Date: 2020-10-12 22:52:37.302014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a395cd9f83ac'
down_revision = 'ac32c8706044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('relay_next_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['relay_next_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'relay_next_id')
    # ### end Alembic commands ###
