"""notes on task

Revision ID: a964bc44716c
Revises: c6613f98c580
Create Date: 2019-05-15 18:41:22.662112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a964bc44716c'
down_revision = 'c6613f98c580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'address', ['uuid'])
    op.create_unique_constraint(None, 'delete_flags', ['uuid'])
    op.create_unique_constraint(None, 'deliverable', ['uuid'])
    op.create_unique_constraint(None, 'note', ['uuid'])
    op.create_unique_constraint(None, 'saved_locations', ['uuid'])
    op.create_unique_constraint(None, 'session', ['uuid'])
    op.create_unique_constraint(None, 'task', ['uuid'])
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.create_unique_constraint(None, 'vehicle', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'task', type_='unique')
    op.drop_constraint(None, 'session', type_='unique')
    op.drop_constraint(None, 'saved_locations', type_='unique')
    op.drop_constraint(None, 'note', type_='unique')
    op.drop_constraint(None, 'deliverable', type_='unique')
    op.drop_constraint(None, 'delete_flags', type_='unique')
    op.drop_constraint(None, 'address', type_='unique')
    # ### end Alembic commands ###
