"""label instead of name for deliverable types

Revision ID: aa4a8f541ac1
Revises: aafaa9468fbd
Create Date: 2020-05-17 04:20:40.170668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4a8f541ac1'
down_revision = 'aafaa9468fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable_type', sa.Column('label', sa.String(), nullable=True))
    op.drop_constraint('deliverable_type_name_key', 'deliverable_type', type_='unique')
    op.create_unique_constraint(None, 'deliverable_type', ['label'])
    op.drop_column('deliverable_type', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable_type', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deliverable_type', type_='unique')
    op.create_unique_constraint('deliverable_type_name_key', 'deliverable_type', ['name'])
    op.drop_column('deliverable_type', 'label')
    # ### end Alembic commands ###
