"""notes and deliverables

Revision ID: abe28b8e8a14
Revises: 1405f424586c
Create Date: 2019-05-02 21:44:03.170396

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'abe28b8e8a14'
down_revision = '1405f424586c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'delete_flags', ['uuid'])
    op.create_unique_constraint(None, 'saved_locations', ['uuid'])
    op.drop_column('saved_locations', 'notes')
    op.create_unique_constraint(None, 'session', ['uuid'])
    op.create_unique_constraint(None, 'task', ['uuid'])
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.create_unique_constraint(None, 'vehicle', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'task', type_='unique')
    op.drop_constraint(None, 'session', type_='unique')
    op.add_column('saved_locations', sa.Column('notes', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saved_locations', type_='unique')
    op.drop_constraint(None, 'delete_flags', type_='unique')
    # ### end Alembic commands ###
