"""added profile_picture_thumbnail_key to user model

Revision ID: ac32c8706044
Revises: 20849c301848
Create Date: 2020-09-29 21:55:12.307753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac32c8706044'
down_revision = '20849c301848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture_thumbnail_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture_thumbnail_key')
    # ### end Alembic commands ###
