"""notes subject

Revision ID: acc41be104a6
Revises: a964bc44716c
Create Date: 2019-05-15 18:58:52.545191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc41be104a6'
down_revision = 'a964bc44716c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('subject', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'subject')
    # ### end Alembic commands ###
