"""reference number on TasksParent model

Revision ID: ae8780b9274f
Revises: 91032dbedd67
Create Date: 2020-11-30 23:53:45.833891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8780b9274f'
down_revision = '91032dbedd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_parent', sa.Column('reference', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks_parent', 'reference')
    # ### end Alembic commands ###
