"""priorities foreign key for tasks

Revision ID: b96170218340
Revises: ae14b053ee90
Create Date: 2019-10-19 17:20:43.398834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96170218340'
down_revision = 'ae14b053ee90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('priority_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'priority', ['priority_id'], ['id'])
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'priority_id')
    op.drop_table('priority')
    # ### end Alembic commands ###
