"""foreign key fixes

Revision ID: bc19fb88e62e
Revises: abe28b8e8a14
Create Date: 2019-05-03 18:51:48.387662

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc19fb88e62e'
down_revision = 'abe28b8e8a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('task', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['task.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=10000), nullable=True),
    sa.Column('task', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('session', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('vehicle', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('deliverable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deliverable'], ['deliverable.id'], ),
    sa.ForeignKeyConstraint(['session'], ['session.uuid'], ),
    sa.ForeignKeyConstraint(['task'], ['task.uuid'], ),
    sa.ForeignKeyConstraint(['user'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['vehicle'], ['vehicle.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('deliverable')
    # ### end Alembic commands ###
