"""ip_address field on LogEntry

Revision ID: bd0192e6895d
Revises: 9cc96dcc78ff
Create Date: 2020-11-18 23:35:23.337336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0192e6895d'
down_revision = '9cc96dcc78ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entry', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entry', 'ip_address')
    # ### end Alembic commands ###
