"""saved locations

Revision ID: c937da1d554b
Revises: 
Create Date: 2019-06-18 19:49:09.261371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c937da1d554b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('flagged_for_deletion', sa.Boolean(), nullable=True),
    sa.Column('address_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_location_timestamp'), 'location', ['timestamp'], unique=False)
    op.drop_index('ix_saved_locations_timestamp', table_name='saved_locations')
    op.drop_table('saved_locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_locations',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('phoneNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('flagged_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.uuid'], name='saved_locations_address_id_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='saved_locations_pkey'),
    sa.UniqueConstraint('uuid', name='saved_locations_uuid_key')
    )
    op.create_index('ix_saved_locations_timestamp', 'saved_locations', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_location_timestamp'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
