"""DeleteFlags uuid for objectId

Revision ID: cb3d85954bf0
Revises: da83d5374730
Create Date: 2019-05-05 12:50:55.919804

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb3d85954bf0'
down_revision = 'da83d5374730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete_flags', sa.Column('objectUUID', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('delete_flags', 'objectId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete_flags', sa.Column('objectId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('delete_flags', 'objectUUID')
    # ### end Alembic commands ###
