"""more consistent time naming for Task

Revision ID: d26942cec718
Revises: 916264802e42
Create Date: 2020-04-07 19:16:31.871171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd26942cec718'
down_revision = '916264802e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('time_cancelled', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('time_dropped_off', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('time_picked_up', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('time_rejected', sa.DateTime(), nullable=True))
    op.drop_column('task', 'pickup_time')
    op.drop_column('task', 'rejected_time')
    op.drop_column('task', 'dropoff_time')
    op.drop_column('task', 'cancelled_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('cancelled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('dropoff_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('rejected_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('pickup_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('task', 'time_rejected')
    op.drop_column('task', 'time_picked_up')
    op.drop_column('task', 'time_dropped_off')
    op.drop_column('task', 'time_cancelled')
    # ### end Alembic commands ###
