"""priorities foreign key for tasks

Revision ID: d62c0f5f8b3c
Revises: f4790c61165f
Create Date: 2019-10-19 17:31:09.411877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62c0f5f8b3c'
down_revision = 'f4790c61165f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sa.Integer(), nullable=True))
    op.drop_constraint('task_priority_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'priority', ['priority'], ['id'])
    op.drop_column('task', 'priority_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_priority_id_fkey', 'task', 'priority', ['priority_id'], ['id'])
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
