"""pickup and dropoff times for task

Revision ID: d6664040d05a
Revises: 1c1264d0041c
Create Date: 2019-08-15 19:41:32.105798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6664040d05a'
down_revision = '1c1264d0041c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('dropoff_time', sa.Time(), nullable=True))
    op.add_column('task', sa.Column('pickup_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'pickup_time')
    op.drop_column('task', 'dropoff_time')
    # ### end Alembic commands ###
