"""patient_name, patient_contact_number, destination_contact_name, destination_contact_number

Revision ID: d7552815fe15
Revises: 1d8d7c4b6f26
Create Date: 2020-03-25 15:14:21.427997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7552815fe15'
down_revision = '1d8d7c4b6f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('destination_contact_name', sa.String(length=64), nullable=True))
    op.add_column('task', sa.Column('destination_contact_number', sa.String(length=64), nullable=True))
    op.add_column('task', sa.Column('patient_contact_number', sa.String(length=64), nullable=True))
    op.add_column('task', sa.Column('patient_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'patient_name')
    op.drop_column('task', 'patient_contact_number')
    op.drop_column('task', 'destination_contact_number')
    op.drop_column('task', 'destination_contact_name')
    # ### end Alembic commands ###
