"""notes

Revision ID: da83d5374730
Revises: 05e735594e70
Create Date: 2019-05-05 12:33:08.223790

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da83d5374730'
down_revision = '05e735594e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('deliverable', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('session', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('note', sa.Column('task', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('note', sa.Column('user', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('note', sa.Column('vehicle', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'note', 'vehicle', ['vehicle'], ['uuid'])
    op.create_foreign_key(None, 'note', 'task', ['task'], ['uuid'])
    op.create_foreign_key(None, 'note', 'deliverable', ['deliverable'], ['id'])
    op.create_foreign_key(None, 'note', 'user', ['user'], ['uuid'])
    op.create_foreign_key(None, 'note', 'session', ['session'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'vehicle')
    op.drop_column('note', 'user')
    op.drop_column('note', 'task')
    op.drop_column('note', 'session')
    op.drop_column('note', 'deliverable')
    # ### end Alembic commands ###
