"""data_fields in LogEntry model

Revision ID: dca2e3e8a5e8
Revises: 1753904231ff
Create Date: 2020-11-07 22:55:40.965889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca2e3e8a5e8'
down_revision = '1753904231ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entry', sa.Column('data_fields', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entry', 'data_fields')
    # ### end Alembic commands ###
