"""vehicle names

Revision ID: dcb02d01f475
Revises: c82263779142
Create Date: 2019-07-14 00:41:51.643991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb02d01f475'
down_revision = 'c82263779142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'vehicle', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle', type_='unique')
    op.drop_column('vehicle', 'name')
    # ### end Alembic commands ###
