"""index uuids

Revision ID: e0162eb623d1
Revises: e165d74da4e1
Create Date: 2021-03-20 23:12:14.576431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0162eb623d1'
down_revision = 'e165d74da4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comment_parent_uuid'), 'comment', ['parent_uuid'], unique=False)
    op.drop_constraint('deliverable_uuid_key', 'deliverable', type_='unique')
    op.create_index(op.f('ix_deliverable_uuid'), 'deliverable', ['uuid'], unique=True)
    op.drop_constraint('location_uuid_key', 'location', type_='unique')
    op.create_index(op.f('ix_location_uuid'), 'location', ['uuid'], unique=True)
    op.drop_constraint('task_uuid_key', 'task', type_='unique')
    op.create_index(op.f('ix_task_uuid'), 'task', ['uuid'], unique=True)
    op.drop_constraint('user_uuid_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.drop_constraint('vehicle_uuid_key', 'vehicle', type_='unique')
    op.create_index(op.f('ix_vehicle_uuid'), 'vehicle', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_uuid'), table_name='vehicle')
    op.create_unique_constraint('vehicle_uuid_key', 'vehicle', ['uuid'])
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.create_unique_constraint('user_uuid_key', 'user', ['uuid'])
    op.drop_index(op.f('ix_task_uuid'), table_name='task')
    op.create_unique_constraint('task_uuid_key', 'task', ['uuid'])
    op.drop_index(op.f('ix_location_uuid'), table_name='location')
    op.create_unique_constraint('location_uuid_key', 'location', ['uuid'])
    op.drop_index(op.f('ix_deliverable_uuid'), table_name='deliverable')
    op.create_unique_constraint('deliverable_uuid_key', 'deliverable', ['uuid'])
    op.drop_index(op.f('ix_comment_parent_uuid'), table_name='comment')
    # ### end Alembic commands ###
