"""move protected flag back to Location model

Revision ID: e165d74da4e1
Revises: 427743e76984
Create Date: 2021-02-04 15:01:45.923715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e165d74da4e1'
down_revision = '427743e76984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'protected')
    op.add_column('location', sa.Column('protected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'protected')
    op.add_column('address', sa.Column('protected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
