"""assigned_user on vehicle instead of assigned_vehicle on user

Revision ID: e83dca7abb9f
Revises: f341929e700f
Create Date: 2020-03-12 01:06:49.237828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e83dca7abb9f'
down_revision = 'f341929e700f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('assigned_user_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('vehicle_assigned_user_fkey', 'vehicle', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle', 'user', ['assigned_user_uuid'], ['uuid'])
    op.drop_column('vehicle', 'assigned_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('assigned_user', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.create_foreign_key('vehicle_assigned_user_fkey', 'vehicle', 'user', ['assigned_user'], ['uuid'])
    op.drop_column('vehicle', 'assigned_user_uuid')
    # ### end Alembic commands ###
