"""assigned_user on vehicle instead of assigned_vehicle on user

Revision ID: f341929e700f
Revises: 628398d591ae
Create Date: 2020-03-12 00:56:39.087701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f341929e700f'
down_revision = '628398d591ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_assigned_vehicle_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'assigned_vehicle')
    op.add_column('vehicle', sa.Column('assigned_user', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'vehicle', 'user', ['assigned_user'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.drop_column('vehicle', 'assigned_user')
    op.add_column('user', sa.Column('assigned_vehicle', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_assigned_vehicle_fkey', 'user', 'vehicle', ['assigned_vehicle'], ['uuid'])
    # ### end Alembic commands ###
