"""wards on address foreign key

Revision ID: f98610529123
Revises: 65e41456e6b2
Create Date: 2019-08-24 18:22:53.662611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98610529123'
down_revision = '65e41456e6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('ward', sa.String(length=64), nullable=True))
    op.drop_column('location', 'ward')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('ward', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('address', 'ward')
    # ### end Alembic commands ###
