"""changed passwordHash to password for paretorian

Revision ID: d7e8214b43aa
Revises: 6f9bc5659e25
Create Date: 2019-01-12 22:12:48.867102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e8214b43aa'
down_revision = '6f9bc5659e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('user', 'passwordHash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwordHash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
