"""Added delete queue

Revision ID: 02401ba52bf5
Revises: 83b55aef3dc3
Create Date: 2019-01-06 17:06:15.927588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02401ba52bf5'
down_revision = '83b55aef3dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delete_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('timeToDelete', sa.Integer(), nullable=True),
    sa.Column('objectType', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delete_flags_timestamp'), 'delete_flags', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('flaggedForDeletion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'flaggedForDeletion')
    op.drop_index(op.f('ix_delete_flags_timestamp'), table_name='delete_flags')
    op.drop_table('delete_flags')
    # ### end Alembic commands ###
