"""Missing objectId item on deleteQueue

Revision ID: 82a15c6c3b60
Revises: 02401ba52bf5
Create Date: 2019-01-06 20:06:51.420800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a15c6c3b60'
down_revision = '02401ba52bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete_flags', sa.Column('objectId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delete_flags', 'objectId')
    # ### end Alembic commands ###
