"""uuids

Revision ID: 11f11c27110b
Revises: 2871747bcee0
Create Date: 2019-04-29 19:45:26.607389

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11f11c27110b'
down_revision = '2871747bcee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete_flags', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'delete_flags', ['uuid'])
    op.add_column('saved_locations', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'saved_locations', ['uuid'])
    op.add_column('session', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'session', ['uuid'])
    op.add_column('task', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'task', ['uuid'])
    op.add_column('user', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.add_column('vehicle', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'vehicle', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle', type_='unique')
    op.drop_column('vehicle', 'uuid')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'uuid')
    op.drop_constraint(None, 'task', type_='unique')
    op.drop_column('task', 'uuid')
    op.drop_constraint(None, 'session', type_='unique')
    op.drop_column('session', 'uuid')
    op.drop_constraint(None, 'saved_locations', type_='unique')
    op.drop_column('saved_locations', 'uuid')
    op.drop_constraint(None, 'delete_flags', type_='unique')
    op.drop_column('delete_flags', 'uuid')
    # ### end Alembic commands ###
