"""flagged for deletion

Revision ID: 2871747bcee0
Revises: 15b4b785e436
Create Date: 2019-02-15 19:01:25.171539

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2871747bcee0'
down_revision = '15b4b785e436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_locations', sa.Column('flaggedForDeletion', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('flaggedForDeletion', sa.Boolean(), nullable=True))
    op.add_column('vehicle', sa.Column('flaggedForDeletion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'flaggedForDeletion')
    op.drop_column('task', 'flaggedForDeletion')
    op.drop_column('saved_locations', 'flaggedForDeletion')
    # ### end Alembic commands ###
